Repository SEKOIA-IO/intake-formats, pull requests merged in 2022-09, with the labels that each got.

#218 Sophos: add host.name
  Sophos/sophos edr/ingest/parser.yml
  Sophos/sophos edr/tests/event_disk_non_encrypted.json
  Sophos/sophos edr/tests/event_encryption_information.json
  Sophos/sophos edr/tests/event_encryption_suspended.json
  Sophos/sophos edr/tests/event_key_received.json
  Sophos/sophos edr/tests/event_outlook_plugin.json
  Sophos/sophos edr/tests/event_registered.json
  Sophos/sophos edr/tests/event_scan_complete.json
  Sophos/sophos edr/tests/event_update_failure.json
  Sophos/sophos edr/tests/event_update_reboot_required.json
  Sophos/sophos edr/tests/event_update_success.json
  Sophos/sophos edr/tests/event_user_auto_created.json
  Sophos/sophos edr/tests/event_webfiltering.json
Labels: enhancement

#203 Sophos: Improve support for dlp and application control events
  Sophos/sophos edr/_meta/fields.yml
  Sophos/sophos edr/_meta/smart-descriptions.json
  Sophos/sophos edr/ingest/parser.yml
  Sophos/sophos edr/tests/event_application_blocked.json
  Sophos/sophos edr/tests/event_dlp_allowed.json
  Sophos/sophos edr/tests/event_dlp_allowed_remote_storage.json
  Sophos/sophos edr/tests/event_exploit_prevention.json
  Sophos/sophos edr/tests/event_pua_detected.json
Labels: enhancement

#176 Microsoft defender for endpoints
  Microsoft Defender/README.md
  Microsoft Defender/_meta/logo.png
  Microsoft Defender/_meta/manifest.yml
  Microsoft Defender/microsoft-defender-for-endpoints/_meta/fields.yml
  Microsoft Defender/microsoft-defender-for-endpoints/_meta/logo.png
  Microsoft Defender/microsoft-defender-for-endpoints/_meta/manifest.yml
  Microsoft Defender/microsoft-defender-for-endpoints/_meta/smart-descriptions.json
  Microsoft Defender/microsoft-defender-for-endpoints/ingest/parser.yml
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_event.json
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_file_certificate_info.json
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_file_event.json
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_image_load_event.json
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_local_ip.json
Labels: enhancement

#226 MDForEndpoint: fix the working directory for a process
  Microsoft Defender/microsoft-defender-for-endpoints/ingest/parser.yml
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_event.json
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_file_event.json
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_device_image_load_event.json
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_local_ip.json
Labels: bug

#231 Retarus: fix parser when sender is empty
  Retarus/retarus_email_security/ingest/parser.yml
  Retarus/retarus_email_security/tests/event_no_sender.json
Labels: bug

#232 TrendMicro: rename the format and enrich the datasources
  Trend Micro/cloud-one/_meta/manifest.yml
  Trend Micro/deep-security/_meta/fields.yml
  Trend Micro/deep-security/_meta/logo.png
  Trend Micro/deep-security/_meta/manifest.yml
  Trend Micro/deep-security/_meta/smart-descriptions.json
  Trend Micro/deep-security/ingest/parser.yml
  Trend Micro/deep-security/tests/AgentAntiMalware.json
  Trend Micro/deep-security/tests/ApplicationControl.json
  Trend Micro/deep-security/tests/DeviceControl.json
  Trend Micro/deep-security/tests/FirewallEventLog.json
  Trend Micro/deep-security/tests/IntegrityMonitoring.json
  Trend Micro/deep-security/tests/IntrusionPrevention.json
  Trend Micro/deep-security/tests/LogInspection.json
  Trend Micro/deep-security/tests/SystemEventLog.json
  Trend Micro/deep-security/tests/WebReputation.json
Labels: enhancement

#219 Add timestamp fields respecting ECS format to event
  Fortinet/fortigate/ingest/parser.yml
  Fortinet/fortigate/tests/Configuration_changed.CEF.json
  Fortinet/fortigate/tests/IP_SEC.STANDARD.json
  Fortinet/fortigate/tests/LOGOUT.STANDARD.json
  Fortinet/fortigate/tests/ROLL-LOG.STANDARD.json
  Fortinet/fortigate/tests/WAD.STANDARD.json
  Fortinet/fortigate/tests/dns.CSV.json
  Fortinet/fortigate/tests/hostname.STANDARD.json
  Fortinet/fortigate/tests/icmp.json
  Fortinet/fortigate/tests/icmp6.json
  Fortinet/fortigate/tests/icmp_CEF.json
  Fortinet/fortigate/tests/ping.json
  Fortinet/fortigate/tests/ssh_access.CEF.json
  Fortinet/fortigate/tests/ssl_new_con.CEF.json
  Fortinet/fortigate/tests/traffic_forward.CEF-Axens.json
  Fortinet/fortigate/tests/traffic_forward.CSV.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD_STET.json
  Fortinet/fortigate/tests/traffic_forward_FTNTFGTtz.CEF.json
  Fortinet/fortigate/tests/traffic_nat.STANDARD.json
  Fortinet/fortigate/tests/tunnel.json
  Fortinet/fortigate/tests/tunnel_statistics.CSV.json
  Fortinet/fortigate/tests/vpn.STANDARD.json
Labels: enhancement

#233 AWS: add support for flowlogs json formatted events
  AWS/aws-flow-logs/ingest/parser.yml
  AWS/aws-flow-logs/tests/accept_structured.json
  AWS/aws-flow-logs/tests/reject_structured.json
Labels: enhancement

#227 AWS: add parser for aws-cloudtrail events
  AWS/aws-cloudtrail/_meta/fields.yml
  AWS/aws-cloudtrail/_meta/smart-descriptions.json
  AWS/aws-cloudtrail/ingest/parser.yml
  AWS/aws-cloudtrail/tests/7602ff70-7e5f-42e9-86b2-36803df39183.json
  AWS/aws-cloudtrail/tests/event_cloudtrail.json
  AWS/aws-cloudtrail/tests/event_ec2-error.json
  AWS/aws-cloudtrail/tests/event_ec2.json
  AWS/aws-cloudtrail/tests/event_iam.json
  AWS/aws-cloudtrail/tests/event_lambda.json
  AWS/aws-cloudtrail/tests/event_rds.json
  AWS/aws-cloudtrail/tests/event_s3.json
  AWS/aws-cloudtrail/tests/event_signin.json
  AWS/aws-cloudtrail/tests/event_sts.json
  AWS/aws-cloudtrail/tests/test_insight.json
  AWS/aws-cloudtrail/tests/test_service_event.json
  AWS/aws-cloudtrail/tests/test_signin2.json
Labels: enhancement

#236 Proofpoint: add format for PoD events
  ProofPoint/proofpoint-pod/_meta/fields.yml
  ProofPoint/proofpoint-pod/_meta/logo.png
  ProofPoint/proofpoint-pod/_meta/manifest.yml
  ProofPoint/proofpoint-pod/_meta/smart-descriptions.json
  ProofPoint/proofpoint-pod/ingest/parser.yml
  ProofPoint/proofpoint-pod/tests/test_maillog.json
  ProofPoint/proofpoint-pod/tests/test_message.json
Labels: enhancement

#238 Proofpoint enhancement
  ProofPoint/proofpoint-pod/_meta/fields.yml
  ProofPoint/proofpoint-pod/ingest/parser.yml
  ProofPoint/proofpoint-pod/tests/test_message.json
  ProofPoint/proofpoint-pod/tests/test_message2.json
Labels: enhancement

#237 AWS: fix smart-descriptions
  AWS/aws-cloudtrail/_meta/fields.yml
  AWS/aws-cloudtrail/_meta/smart-descriptions.json
Labels: bug

#239 Symantec EPP: fix parser
  Broadcom/symantec-endpoint-protection/_meta/smart-descriptions.json
  Broadcom/symantec-endpoint-protection/ingest/parser.yml
  Broadcom/symantec-endpoint-protection/tests/test_behavior_logs.json
Labels: bug, enhancement

#241 Proofpoint: Add smtp envelope information
  ProofPoint/proofpoint-pod/_meta/fields.yml
  ProofPoint/proofpoint-pod/_meta/smart-descriptions.json
  ProofPoint/proofpoint-pod/ingest/parser.yml
  ProofPoint/proofpoint-pod/tests/test_message.json
  ProofPoint/proofpoint-pod/tests/test_message2.json
  ProofPoint/proofpoint-pod/tests/test_message3.json
Labels: enhancement

#243 AWS: Extract new fields
  AWS/aws-cloudtrail/_meta/fields.yml
  AWS/aws-cloudtrail/ingest/parser.yml
  AWS/aws-cloudtrail/tests/event_iam.json
Labels: enhancement

#133 GateWatcher: Push the AIONIQ format
  GateWatcher/README.md
  GateWatcher/_meta/logo.png
  GateWatcher/_meta/manifest.yml
  GateWatcher/aioniq/_meta/fields.yml
  GateWatcher/aioniq/_meta/logo.png
  GateWatcher/aioniq/_meta/manifest.yml
  GateWatcher/aioniq/_meta/smart-descriptions.json
  GateWatcher/aioniq/ingest/parser.yml
  GateWatcher/aioniq/tests/malcore_event.json
  GateWatcher/aioniq/tests/suricata_alert_event.json
  GateWatcher/aioniq/tests/suricata_fileinfo_event.json
  GateWatcher/aioniq/tests/suricata_http_event.json
Labels: enhancement

#240 fix/Windows_defender/add_DetectionSource
  Microsoft Defender/microsoft-defender-for-endpoints/_meta/fields.yml
  Microsoft Defender/microsoft-defender-for-endpoints/_meta/smart-descriptions.json
  Microsoft Defender/microsoft-defender-for-endpoints/ingest/parser.yml
  Microsoft Defender/microsoft-defender-for-endpoints/tests/test_detection_source.json
Labels: good first issue

#247 Update parser.yml
  Fortinet/fortigate/ingest/parser.yml
  Fortinet/fortigate/tests/IP_SEC.STANDARD.json
  Fortinet/fortigate/tests/LOGOUT.STANDARD.json
  Fortinet/fortigate/tests/ROLL-LOG.STANDARD.json
  Fortinet/fortigate/tests/WAD.STANDARD.json
  Fortinet/fortigate/tests/hostname.STANDARD.json
  Fortinet/fortigate/tests/icmp.json
  Fortinet/fortigate/tests/icmp6.json
  Fortinet/fortigate/tests/ping.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD_2.json
  Fortinet/fortigate/tests/traffic_nat.STANDARD.json
  Fortinet/fortigate/tests/tunnel.json
  Fortinet/fortigate/tests/tunnel_statistics.CSV.json
  Fortinet/fortigate/tests/vpn.STANDARD.json
Labels: enhancement
