Repository SEKOIA-IO/intake-formats, pull requests merged in 2022-10, with the labels that each got.

#249 add format for Microsoft Always on VPN
  Windows/_meta/manifest.yml
  Windows/microsoft-always-on-vpn/_meta/fields.yml
  Windows/microsoft-always-on-vpn/_meta/logo.png
  Windows/microsoft-always-on-vpn/_meta/manifest.yml
  Windows/microsoft-always-on-vpn/_meta/smart-descriptions.json
  Windows/microsoft-always-on-vpn/ingest/parser.yml
  Windows/microsoft-always-on-vpn/tests/access_accept_event.json
  Windows/microsoft-always-on-vpn/tests/access_challenge_event.json
  Windows/microsoft-always-on-vpn/tests/access_request_event.json
  Windows/microsoft-always-on-vpn/tests/accounting_request_event.json
Labels: enhancement

#245 Forcepoint: split username and domain
  Forcepoint/forcepoint-swg/ingest/parser.yml
  Forcepoint/forcepoint-swg/tests/test_transaction_permitted.json
Labels: bug

#255 Feat improve fortinet
  Fortinet/fortigate/_meta/manifest.yml
  Fortinet/fortigate/_meta/smart-descriptions.json
  Fortinet/fortigate/ingest/parser.yml
  Fortinet/fortigate/tests/DLP.CEF.json
  Fortinet/fortigate/tests/DNS.CEF.json
  Fortinet/fortigate/tests/IPS.CEF.json
  Fortinet/fortigate/tests/IP_SEC.STANDARD.json
  Fortinet/fortigate/tests/LOGOUT.STANDARD.json
  Fortinet/fortigate/tests/ROLL-LOG.STANDARD.json
  Fortinet/fortigate/tests/SSH.CEF-2.json
  Fortinet/fortigate/tests/VoIP.CEF.json
  Fortinet/fortigate/tests/WAD.STANDARD.json
  Fortinet/fortigate/tests/WAF.CEF.json
  Fortinet/fortigate/tests/anomaly.CEF-2.json
  Fortinet/fortigate/tests/anomaly.CEF.json
  Fortinet/fortigate/tests/anomaly.CSV.json
  Fortinet/fortigate/tests/anomaly.STANDARD.json
  Fortinet/fortigate/tests/antivirus.CEF-2.json
  Fortinet/fortigate/tests/antivirus.CEF.json
  Fortinet/fortigate/tests/application.CEF.json
  Fortinet/fortigate/tests/dns.CSV.json
  Fortinet/fortigate/tests/email-spamfilter.CEF.json
  Fortinet/fortigate/tests/event_log_system_subtype.CEF.json
  Fortinet/fortigate/tests/event_log_user_subtype.CEF.json
  Fortinet/fortigate/tests/hostname.STANDARD.json
  Fortinet/fortigate/tests/icmp.json
  Fortinet/fortigate/tests/icmp6.json
  Fortinet/fortigate/tests/icmp_CEF.json
  Fortinet/fortigate/tests/ping.json
  Fortinet/fortigate/tests/ssh_access.CEF.json
  Fortinet/fortigate/tests/ssl_new_con.CEF.json
  Fortinet/fortigate/tests/traffic_forward.CEF-2.json
  Fortinet/fortigate/tests/traffic_forward.CEF-3.json
  Fortinet/fortigate/tests/traffic_forward.CEF.json
  Fortinet/fortigate/tests/traffic_forward.CSV.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD_2.json
  Fortinet/fortigate/tests/traffic_forward_FTNTFGTtz.CEF.json
  Fortinet/fortigate/tests/traffic_nat.STANDARD.json
  Fortinet/fortigate/tests/tunnel.json
  Fortinet/fortigate/tests/tunnel_statistics.CSV.json
  Fortinet/fortigate/tests/vpn.STANDARD.json
  Fortinet/fortigate/tests/webfilter.CEF.json
Labels: enhancement

#267 Symantec: fixes
  Broadcom/symantec-endpoint-protection/_meta/fields.yml
  Broadcom/symantec-endpoint-protection/_meta/smart-descriptions.json
  Broadcom/symantec-endpoint-protection/ingest/parser.yml
  Broadcom/symantec-endpoint-protection/tests/test_activity_logs.json
  Broadcom/symantec-endpoint-protection/tests/test_behavior_logs.json
  Broadcom/symantec-endpoint-protection/tests/test_scan.json
  Broadcom/symantec-endpoint-protection/tests/test_sonar.json
  Broadcom/symantec-endpoint-protection/tests/test_system_logs.json
  Broadcom/symantec-endpoint-protection/tests/test_virus_found2.json
Labels: bug

#270 Watchguard: add parser for firebox events
  WatchGuard/README.md
  WatchGuard/_meta/logo.png
  WatchGuard/_meta/manifest.yml
  WatchGuard/watchguard-firebox/_meta/fields.yml
  WatchGuard/watchguard-firebox/_meta/logo.png
  WatchGuard/watchguard-firebox/_meta/manifest.yml
  WatchGuard/watchguard-firebox/_meta/smart-descriptions.json
  WatchGuard/watchguard-firebox/ingest/parser.yml
  WatchGuard/watchguard-firebox/tests/connection.json
  WatchGuard/watchguard-firebox/tests/connection_allow.json
  WatchGuard/watchguard-firebox/tests/connection_allow2.json
  WatchGuard/watchguard-firebox/tests/connection_allow3.json
  WatchGuard/watchguard-firebox/tests/connection_deny.json
  WatchGuard/watchguard-firebox/tests/dhcp_pack.json
  WatchGuard/watchguard-firebox/tests/dhcp_request.json
  WatchGuard/watchguard-firebox/tests/dpi_http_1.json
  WatchGuard/watchguard-firebox/tests/dpi_http_2.json
  WatchGuard/watchguard-firebox/tests/dpi_http_deny.json
  WatchGuard/watchguard-firebox/tests/game_allow.json
  WatchGuard/watchguard-firebox/tests/geo_deny.json
  WatchGuard/watchguard-firebox/tests/no_rule_deny.json
  WatchGuard/watchguard-firebox/tests/virus_analysis.json
Labels: enhancement

#271 Fortigate: fix fields
  Fortinet/fortigate/_meta/fields.yml
  Fortinet/fortigate/ingest/parser.yml
  Fortinet/fortigate/tests/IP_SEC.STANDARD.json
  Fortinet/fortigate/tests/LOGOUT.STANDARD.json
  Fortinet/fortigate/tests/ROLL-LOG.STANDARD.json
  Fortinet/fortigate/tests/WAD.STANDARD.json
  Fortinet/fortigate/tests/anomaly.CSV.json
  Fortinet/fortigate/tests/anomaly.STANDARD.json
  Fortinet/fortigate/tests/dns.CSV.json
  Fortinet/fortigate/tests/hostname.STANDARD.json
  Fortinet/fortigate/tests/icmp.json
  Fortinet/fortigate/tests/icmp6.json
  Fortinet/fortigate/tests/ping.json
  Fortinet/fortigate/tests/traffic_forward.CSV.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD_2.json
  Fortinet/fortigate/tests/traffic_nat.STANDARD.json
  Fortinet/fortigate/tests/tunnel.json
  Fortinet/fortigate/tests/tunnel_statistics.CSV.json
  Fortinet/fortigate/tests/vpn.STANDARD.json
  Fortinet/fortigate/tests/vpn_login_failed.STANDARD.json
Labels: enhancement

#272 Symantec: little fix
  Broadcom/symantec-endpoint-protection/ingest/parser.yml
  Broadcom/symantec-endpoint-protection/tests/test_liveupdate.json
Labels: bug

#275 feat(o365): Remove some properties fields and move others to office365
  Office 365/o365/_meta/fields.yml
  Office 365/o365/ingest/parser.yml
  Office 365/o365/tests/ad.json
  Office 365/o365/tests/update_user_empty_source_ip.json
  Office 365/o365/tests/user_logged_in.json
  Office 365/o365/tests/user_login_failed.json
Labels: enhancement

#254 Crowdstrike: add support for new events
  CrowdStrike/crowdstrike_falcon/_meta/fields.yml
  CrowdStrike/crowdstrike_falcon/_meta/smart-descriptions.json
  CrowdStrike/crowdstrike_falcon/ingest/parser.yml
  CrowdStrike/crowdstrike_falcon/tests/detection_summary_event.json
  CrowdStrike/crowdstrike_falcon/tests/device_event.json
  CrowdStrike/crowdstrike_falcon/tests/module_event.json
  CrowdStrike/crowdstrike_falcon/tests/process_event.json
  CrowdStrike/crowdstrike_falcon/tests/stream_started.json
  CrowdStrike/crowdstrike_falcon/tests/stream_stopped.json
  CrowdStrike/crowdstrike_falcon/tests/user_event.json
  CrowdStrike/crowdstrike_falcon/tests/user_session_event.json
Labels: enhancement

#279 Fortinet: extract DeviceEventClassId from the CEF message
  Fortinet/fortigate/ingest/parser.yml
  Fortinet/fortigate/tests/traffic_forward-RDP.CEF.json
Labels: bug

#281 Fortinet: add network.bytes and fix usernames
  Fortinet/fortigate/ingest/parser.yml
  Fortinet/fortigate/tests/icmp6.json
  Fortinet/fortigate/tests/icmp_CEF.json
  Fortinet/fortigate/tests/ping.json
  Fortinet/fortigate/tests/ssl_new_con.CEF.json
  Fortinet/fortigate/tests/traffic_forward-RDP.CEF.json
  Fortinet/fortigate/tests/traffic_forward.CEF-2.json
  Fortinet/fortigate/tests/traffic_forward.CEF-3.json
  Fortinet/fortigate/tests/traffic_forward.CEF.json
  Fortinet/fortigate/tests/traffic_forward.CSV.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD.json
  Fortinet/fortigate/tests/traffic_forward.STANDARD_2.json
  Fortinet/fortigate/tests/traffic_nat.STANDARD.json
  Fortinet/fortigate/tests/tunnel.json
  Fortinet/fortigate/tests/tunnel_statistics.CSV.json
  Fortinet/fortigate/tests/webfilter.CEF.json
Labels: bug

#282 Fortigate: fix severity
  Fortinet/fortigate/_meta/smart-descriptions.json
  Fortinet/fortigate/ingest/parser.yml
  Fortinet/fortigate/tests/Configuration_changed.CEF.json
  Fortinet/fortigate/tests/DLP.CEF.json
  Fortinet/fortigate/tests/DNS.CEF.json
  Fortinet/fortigate/tests/IPS.CEF.json
  Fortinet/fortigate/tests/SSH.CEF-2.json
  Fortinet/fortigate/tests/VoIP.CEF.json
  Fortinet/fortigate/tests/WAF.CEF.json
  Fortinet/fortigate/tests/anomaly.CEF-2.json
  Fortinet/fortigate/tests/anomaly.CEF.json
  Fortinet/fortigate/tests/antivirus.CEF-2.json
  Fortinet/fortigate/tests/antivirus.CEF.json
  Fortinet/fortigate/tests/application.CEF.json
  Fortinet/fortigate/tests/email-spamfilter.CEF.json
  Fortinet/fortigate/tests/event_log_system_subtype.CEF.json
  Fortinet/fortigate/tests/event_log_user_subtype.CEF.json
  Fortinet/fortigate/tests/icmp_CEF.json
  Fortinet/fortigate/tests/ssh_access.CEF.json
  Fortinet/fortigate/tests/ssl_new_con.CEF.json
  Fortinet/fortigate/tests/traffic_forward-RDP.CEF.json
  Fortinet/fortigate/tests/traffic_forward.CEF-2.json
  Fortinet/fortigate/tests/traffic_forward.CEF-3.json
  Fortinet/fortigate/tests/traffic_forward.CEF.json
  Fortinet/fortigate/tests/traffic_forward_FTNTFGTtz.CEF.json
  Fortinet/fortigate/tests/webfilter.CEF.json
Labels: bug, enhancement
