Repository SEKOIA-IO/intake-formats, pull requests merged in 2022-07, with the labels that each got.

#141 Office365: remove the extract of url.original from teams links
  Office 365/o365/ingest/parser.yml
  Office 365/o365/tests/teams_message_has_link.json
Labels: bug

#157 Infoblox: Add new format for Infoblox DDI
  Infoblox/README.md
  Infoblox/_meta/logo.png
  Infoblox/_meta/manifest.yml
  Infoblox/ddi/_meta/logo.png
  Infoblox/ddi/_meta/manifest.yml
  Infoblox/ddi/_meta/smart-descriptions.json
  Infoblox/ddi/ingest/parser.yml
  Infoblox/ddi/tests/query_log.json
  Infoblox/ddi/tests/query_log_cd.json
  Infoblox/ddi/tests/query_log_dnssec.json
  Infoblox/ddi/tests/query_log_edns_version.json
  Infoblox/ddi/tests/query_log_no_recursion.json
  Infoblox/ddi/tests/query_log_reverse.json
  Infoblox/ddi/tests/query_log_tcp.json
Labels: enhancement

#158 Miscellaneous improvements
  Acklio/acklio/_meta/manifest.yml
  Cyberwatch/_meta/logo.png
  Cyberwatch/_meta/manifest.yml
  Cyberwatch/cyberwatch/_meta/manifest.yml
  F-Secure/fsecure-av/_meta/manifest.yml
  F5 Networks/_meta/manifest.yml
  FreeRADIUS/freeradius/_meta/manifest.yml
  Imperva/imperva-waf/_meta/manifest.yml
  Log Insight Windows/_meta/manifest.yml
  Pradeo/_meta/logo.png
  Pradeo/pradeo/_meta/logo.png
  Pradeo/pradeo/_meta/manifest.yml
  Wallix/_meta/manifest.yml
  Wallix/wallix-bastion/_meta/manifest.yml
Labels: bug, enhancement

#160 Tooling: add format generator
  utils/generate.py
  utils/new_intake/{{cookiecutter.intake_slug}}/_meta/manifest.yml
  utils/new_intake/{{cookiecutter.intake_slug}}/_meta/smart-descriptions.json
  utils/new_module/{{cookiecutter.module_dir}}/_meta/manifest.yml
  utils/poetry.lock
  utils/pyproject.toml
Labels: enhancement

#159 Add new format for Bind
  BIND/bind/_meta/smart-descriptions.json
  BIND/bind/ingest/parser.yml
  BIND/bind/tests/query_log.json
  BIND/bind/tests/query_log_cd.json
  BIND/bind/tests/query_log_dnssec.json
  BIND/bind/tests/query_log_edns_version.json
  BIND/bind/tests/query_log_no_recursion.json
  BIND/bind/tests/query_log_reverse.json
  BIND/bind/tests/query_log_tcp.json
Labels: enhancement

#142 Office365: add support for Microsoft Defender for o365 email events
  Office 365/o365/_meta/fields.yml
  Office 365/o365/ingest/parser.yml
  Office 365/o365/tests/microsoft_defender_threatintelligence_atp.json
  Office 365/o365/tests/microsoft_defender_threatintelligence_mail.json
  Office 365/o365/tests/microsoft_defender_threatintelligence_url_click.json
Labels: enhancement

#161 ProofPoint: add new intake for proofpoint TAP events
  ProofPoint/README.md
  ProofPoint/_meta/logo.png
  ProofPoint/_meta/manifest.yml
  ProofPoint/proofpoint-tap/_meta/fields.yml
  ProofPoint/proofpoint-tap/_meta/logo.png
  ProofPoint/proofpoint-tap/_meta/manifest.yml
  ProofPoint/proofpoint-tap/_meta/smart-descriptions.json
  ProofPoint/proofpoint-tap/ingest/parser.yml
  ProofPoint/proofpoint-tap/tests/test_click_permitted.json
  ProofPoint/proofpoint-tap/tests/test_message_blocked.json
Labels: enhancement

#153 NetFlow: add new format
  NetFlow/README.md
  NetFlow/_meta/logo.png
  NetFlow/_meta/manifest.yml
  NetFlow/netflow/_meta/fields.yml
  NetFlow/netflow/_meta/logo.png
  NetFlow/netflow/_meta/manifest.yml
  NetFlow/netflow/_meta/smart-descriptions.json
  NetFlow/netflow/ingest/parser.yml
  NetFlow/netflow/tests/ipfix.json
  NetFlow/netflow/tests/netflow_v5.json
  NetFlow/netflow/tests/netflow_v9.json
Labels: enhancement

#123 Forcepoint
  Forcepoint/README.md
  Forcepoint/_meta/logo.png
  Forcepoint/_meta/manifest.yml
  Forcepoint/forcepoint-swg/_meta/fields.yml
  Forcepoint/forcepoint-swg/_meta/logo.png
  Forcepoint/forcepoint-swg/_meta/manifest.yml
  Forcepoint/forcepoint-swg/_meta/smart-descriptions.json
  Forcepoint/forcepoint-swg/ingest/parser.yml
  Forcepoint/forcepoint-swg/tests/test_transaction_blocked.json
  Forcepoint/forcepoint-swg/tests/test_transaction_permitted.json
Labels: enhancement

#168 VadeSecure: extract the action done on the message
  VadeSecure/vade_secure_m365/ingest/parser.yml
  VadeSecure/vade_secure_m365/tests/email.json
Labels: enhancement

#167 SentinelOne: fix the representation of dates
  SentinelOne/sentinelone/ingest/parser.yml
  SentinelOne/sentinelone/tests/custom_rule.json
  SentinelOne/sentinelone/tests/custom_rule2.json
Labels: bug

#173 ProofPointTAP: fix reply_to.address
  ProofPoint/proofpoint-tap/ingest/parser.yml
Labels: bug

#172 SentinelOne: only parse defined dates
  SentinelOne/sentinelone/ingest/parser.yml
Labels: bug

#177 feat(crowdstrike): Smart description and relationships
  CrowdStrike/crowdstrike_falcon/_meta/smart-descriptions.json
Labels: enhancement

#178 Cloudflare: some rewording
  Cloudflare/firewall_events/_meta/manifest.yml
  Cloudflare/http_requests/_meta/manifest.yml
Labels: enhancement
