Repository SEKOIA-IO/intake-formats, pull requests merged in 2022-04, with the labels that each got.

#82 Cisco: handle syslog prefixed payload
  Cisco/cisco-wsa/ingest/parser.yml
  Cisco/cisco-wsa/tests/event1.json
  Cisco/cisco-wsa/tests/prefixed.json
Labels: bug

#84 Cisco: set the timestamp of the event
  Cisco/cisco-wsa/ingest/parser.yml
Labels: enhancement

#85 Cisco: add timestamp in the test
  Cisco/cisco-wsa/tests/event1.json
  Cisco/cisco-wsa/tests/prefixed.json
  Cisco/cisco-wsa/tests/w3c.json
Labels: bug

#96 fix(imperva): fix date parsing
  Imperva/imperva-waf/ingest/parser.yml
  Imperva/imperva-waf/tests/access.json
  Imperva/imperva-waf/tests/access_security.json
Labels: bug

#101 SentinelOne: fix process name
  SentinelOne/deep_visibility/ingest/parser.yml
  SentinelOne/deep_visibility/tests/behavioral_indicators.json
  SentinelOne/deep_visibility/tests/event_dns.json
  SentinelOne/deep_visibility/tests/file_creation.json
  SentinelOne/deep_visibility/tests/file_creation2.json
  SentinelOne/deep_visibility/tests/file_creation_missing_fields.json
  SentinelOne/deep_visibility/tests/file_deletion.json
  SentinelOne/deep_visibility/tests/file_modification.json
  SentinelOne/deep_visibility/tests/http.json
  SentinelOne/deep_visibility/tests/open_process.json
  SentinelOne/deep_visibility/tests/process_creation.json
  SentinelOne/deep_visibility/tests/process_exit.json
  SentinelOne/deep_visibility/tests/reg_key_security_changed.json
  SentinelOne/deep_visibility/tests/reg_value_create.json
  SentinelOne/deep_visibility/tests/reg_value_delete.json
  SentinelOne/deep_visibility/tests/reg_value_modified.json
  SentinelOne/deep_visibility/tests/sched_task_update.json
  SentinelOne/deep_visibility/tests/script.json
  SentinelOne/deep_visibility/tests/tcpv4.json
Labels: bug

#105 Imperva: Improve the parser
  Imperva/imperva-waf/ingest/parser.yml
  Imperva/imperva-waf/tests/access.json
  Imperva/imperva-waf/tests/access_security_bad.json
  Imperva/imperva-waf/tests/access_security_blacklisted.json
  Imperva/imperva-waf/tests/access_security_blocked.json
  Imperva/imperva-waf/tests/access_security_cached.json
  Imperva/imperva-waf/tests/access_security_challenged.json
  Imperva/imperva-waf/tests/access_security_ipv6_not_supported.json
  Imperva/imperva-waf/tests/access_security_passed.json
  Imperva/imperva-waf/tests/access_security_unresolved.json
Labels: bug, enhancement
