Repository SEKOIA-IO/intake-formats, pull requests merged in 2023-08, with the labels that each got.

#657 Fix/squid/squid/timestamp correction
  Squid/squid/ingest/parser.yml
  Squid/squid/tests/connect.json
  Squid/squid/tests/connect2.json
  Squid/squid/tests/connect3.json
  Squid/squid/tests/connect_ip.json
  Squid/squid/tests/content_type.json
  Squid/squid/tests/get.json
  Squid/squid/tests/get2.json
  Squid/squid/tests/get_dalid.json
  Squid/squid/tests/get_tcp_hit.json
  Squid/squid/tests/get_user_agent.json
Labels: hackathon

#619 feat(Office 365): Parse ExchangeAdmin parameters
  Office 365/o365/_meta/fields.yml
  Office 365/o365/ingest/parser.yml
  Office 365/o365/tests/inbox_rule.json
Labels: enhancement

#648 Fix the timestamp problem
  Palo Alto Networks/paloalto-ngfw/ingest/parser.yml
  Palo Alto Networks/paloalto-ngfw/tests/User_id_1_csv.json
  Palo Alto Networks/paloalto-ngfw/tests/User_id_2_csv.json
  Palo Alto Networks/paloalto-ngfw/tests/fix_bug_with_int.json
  Palo Alto Networks/paloalto-ngfw/tests/fix_bug_without_int.json
  Palo Alto Networks/paloalto-ngfw/tests/globalprotect_csv.json
  Palo Alto Networks/paloalto-ngfw/tests/globalprotect_csv_2.json
  Palo Alto Networks/paloalto-ngfw/tests/icmp_allow_csv.json
  Palo Alto Networks/paloalto-ngfw/tests/system_csv.json
  Palo Alto Networks/paloalto-ngfw/tests/tcp_allow_csv.json
  Palo Alto Networks/paloalto-ngfw/tests/test_timestamp_palo.json
  Palo Alto Networks/paloalto-ngfw/tests/threat_csv.json
  Palo Alto Networks/paloalto-ngfw/tests/traffic_cef.json
  Palo Alto Networks/paloalto-ngfw/tests/udp_deny_csv.json
  Palo Alto Networks/paloalto-ngfw/tests/url_cef.json
Labels: hackathon

#654 fix STR dict problem for paloalto field
  Palo Alto Networks/paloalto-ngfw/ingest/parser.yml
  Palo Alto Networks/paloalto-ngfw/tests/test_timestamp_palo.json
Labels: hackathon

#664 Add smart desc to checkpoint
  Checkpoint/checkpoint/_meta/smart-descriptions.json
Labels: hackathon

#655 fix cloudflare http request parser
  Cloudflare/http_requests/ingest/parser.yml
Labels: bug, hackathon

#662 Fix/crowdstrike/telemetry/add ts
  CrowdStrike/crowdstrike-telemetry/ingest/parser.yml
  CrowdStrike/crowdstrike-telemetry/tests/telemetry_event_31.json
  CrowdStrike/crowdstrike-telemetry/tests/telemetry_event_32.json
  CrowdStrike/crowdstrike-telemetry/tests/telemetry_event_36.json
Labels: hackathon

#661 Changing intake name for cisco esa small typo
  Cisco/cisco-esa/_meta/manifest.yml
Labels: hackathon

#615 Trellix: some fixes
  Trellix/README.md
  Trellix/trellix-epo/CHANGELOG.md
  Trellix/trellix-epo/_meta/smart-descriptions.json
  Trellix/trellix-epo/ingest/parser.yml
  Trellix/trellix-epo/tests/epo_event.json
Labels: bug, enhancement

#693 CrowdStrike: add smart-descriptions for IDP events
  CrowdStrike/crowdstrike_falcon/_meta/smart-descriptions.json
Labels: enhancement

#697 OpenBSD: apply smart descriptions for UDP events
  OpenBSD/openbsd-packet-filter/CHANGELOG.md
  OpenBSD/openbsd-packet-filter/_meta/smart-descriptions.json
  OpenBSD/openbsd-packet-filter/ingest/parser.yml
Labels: enhancement

#703 CatoSASE: add beta flag
  CatoNetworks/cato-sase/CHANGELOG.md
  CatoNetworks/cato-sase/_meta/manifest.yml
Labels: enhancement
